---
name: scheduler

releases:
- name: ocf-scheduler
  version: 0.0.3
  url: git+https://github.com/starkandwayne/ocf-scheduler-boshrelease

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: ocf-scheduler
  azs: [z1]
  instances: 1
  jobs:
  - name: scheduler
    release: ocf-scheduler
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
- name: smoke-tests
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: smoke-tests
    release: ocf-scheduler
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
